config/routes.rb
SistemaColaborativoSeguranca::Application.routes.draw do
  
  resources :convites

  resources :comentarios

  resources :atendimentos

  resources :grupo_colaborativos do
    post 'remove_usuario'
  end

  resources :alarmes

  resources :sensors

  resources :tipo_sensors

  resources :enderecos

  devise_for :usuarios

  resources :usuarios do
    collection do 
      post :register_device
      post :unregister_device
    end
  end

  root :to => "sensors#index"

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  self.include_root_in_json = true
  attr_accessible :alarme_id, :data, :mensagem, :usuario_id
  belongs_to :usuario
  belongs_to :alarme
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    respond_to do |format|
      format.html { 
        logger.info "From HTML"
        @comentario = Comentario.new(params[:comentario])
        @comentario.usuario = current_usuario
        if @comentario.save
          redirect_to @comentario, notice: 'Comentario was successfully created.' 
        else
          render action: "new"
        end
      }
      format.json {
        logger.info "From JSON"
        @comentario = Comentario.new
        @comentario.attributes = ActiveSupport::JSON.decode(params[:comentario])
        @comentario.usuario = current_usuario
        if @comentario.save
         render json: @comentario.to_json(:include => [:usuario]), status: :created, location: @comentario
        else
          render json: @comentario.errors, status: :unprocessable_entity
        end
      }
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mensagem %><br />
    <%= f.text_field :mensagem %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :alarme_id %><br />
    <%= f.number_field :alarme_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Mensagem</th>
    <th>Usuario</th>
    <th>Alarme</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.mensagem %></td>
    <td><%= comentario.usuario_id %></td>
    <td><%= comentario.alarme_id %></td>
    <td><%= comentario.data %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mensagem:</b>
  <%= @comentario.mensagem %>
</p>

<p>
  <b>Usuario:</b>
  <%= @comentario.usuario_id %>
</p>

<p>
  <b>Alarme:</b>
  <%= @comentario.alarme_id %>
</p>

<p>
  <b>Data:</b>
  <%= @comentario.data %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>