config/routes.rb
SistemaColaborativoSeguranca::Application.routes.draw do
  
  resources :convites

  resources :comentarios

  resources :atendimentos

  resources :grupo_colaborativos do
    post 'remove_usuario'
  end

  resources :alarmes

  resources :sensors

  resources :tipo_sensors

  resources :enderecos

  devise_for :usuarios

  resources :usuarios do
    collection do 
      post :register_device
      post :unregister_device
    end
  end

  root :to => "sensors#index"

end

app/models/convite.rb
class Convite < ActiveRecord::Base
  self.include_root_in_json = true
  attr_accessible :email_destinatario, :email_remetente, :grupo_id, :grupo_nome, :nome_remetente
end

app/controllers/convites_controller.rb
class ConvitesController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /convites
  # GET /convites.json
  def index
    logger.info current_usuario.email
    @convites = Convite.where(:email_destinatario => current_usuario.email)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @convites }
    end
  end

  # GET /convites/1
  # GET /convites/1.json
  def show
    @convite = Convite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @convite }
    end
  end

  # GET /convites/new
  # GET /convites/new.json
  def new
    @convite = Convite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @convite }
    end
  end

  # GET /convites/1/edit
  def edit
    @convite = Convite.find(params[:id])
  end

  # POST /convites
  # POST /convites.json
  def create
    respond_to do |format|
      format.html { 
        logger.info "From HTML"
        @convite = Convite.new(params[:convite])
        if @convite.save
          redirect_to @convite, notice: 'Convite was successfully created.' 
        else
          render action: "new"
        end
      }
      format.json {
        logger.info "From JSON"
        @convite = Convite.new
        @convite.attributes = ActiveSupport::JSON.decode(params[:convite])
        addUserInfoToConvite(@convite)
        if @convite.save
         ConviteMailer.send_convite(@convite).deliver  
         render json: @convite, status: :created, location: @convite
        else
          render json: @convite.errors, status: :unprocessable_entity
        end
      }
    end
  end

  def addUserInfoToConvite(convite)
    convite.email_remetente = current_usuario.email
    convite.nome_remetente = current_usuario.name
  end

  # PUT /convites/1
  # PUT /convites/1.json
  def update
    @convite = Convite.find(params[:id])

    grupo = GrupoColaborativo.find(@convite.grupo_id)
    usuario = Usuario.where(:email => @convite.email_destinatario)
    if grupo.usuarios.find_by_id(usuario).nil?
      logger.info "Usuário vai ser inscrito no grupo"
      grupo.usuarios << usuario
      grupo.update_attributes(:email_dono => grupo.email_dono)
    end
    @convite.destroy

    respond_to do |format|
      format.html { redirect_to convites_url }
      format.json { head :no_content }
    end
  end

  # DELETE /convites/1
  # DELETE /convites/1.json
  def destroy
    @convite = Convite.find(params[:id])
    @convite.destroy

    respond_to do |format|
      format.html { redirect_to convites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/convites_helper.rb
module ConvitesHelper
end

app/views/convites/_form.html.erb
<%= form_for(@convite) do |f| %>
  <% if @convite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convite.errors.count, "error") %> prohibited this convite from being saved:</h2>

      <ul>
      <% @convite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email_remetente %><br />
    <%= f.text_field :email_remetente %>
  </div>
  <div class="field">
    <%= f.label :email_destinatario %><br />
    <%= f.text_field :email_destinatario %>
  </div>
  <div class="field">
    <%= f.label :grupo_id %><br />
    <%= f.text_field :grupo_id %>
  </div>
  <div class="field">
    <%= f.label :grupo_nome %><br />
    <%= f.text_field :grupo_nome %>
  </div>
  <div class="field">
    <%= f.label :nome_remetente %><br />
    <%= f.text_field :nome_remetente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/convites/edit.html.erb
<h1>Editing convite</h1>

<%= render 'form' %>

<%= link_to 'Show', @convite %> |
<%= link_to 'Back', convites_path %>

app/views/convites/index.html.erb
<h1>Listing convites</h1>

<table>
  <tr>
    <th>Email remetente</th>
    <th>Email destinatario</th>
    <th>Grupo</th>
    <th>Grupo nome</th>
    <th>Nome remetente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convites.each do |convite| %>
  <tr>
    <td><%= convite.email_remetente %></td>
    <td><%= convite.email_destinatario %></td>
    <td><%= convite.grupo_id %></td>
    <td><%= convite.grupo_nome %></td>
    <td><%= convite.nome_remetente %></td>
    <td><%= link_to 'Show', convite %></td>
    <td><%= link_to 'Edit', edit_convite_path(convite) %></td>
    <td><%= link_to 'Destroy', convite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Convite', new_convite_path %>

app/views/convites/new.html.erb
<h1>New convite</h1>

<%= render 'form' %>

<%= link_to 'Back', convites_path %>

app/views/convites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email remetente:</b>
  <%= @convite.email_remetente %>
</p>

<p>
  <b>Email destinatario:</b>
  <%= @convite.email_destinatario %>
</p>

<p>
  <b>Grupo:</b>
  <%= @convite.grupo_id %>
</p>

<p>
  <b>Grupo nome:</b>
  <%= @convite.grupo_nome %>
</p>

<p>
  <b>Nome remetente:</b>
  <%= @convite.nome_remetente %>
</p>


<%= link_to 'Edit', edit_convite_path(@convite) %> |
<%= link_to 'Back', convites_path %>