config/routes.rb
SistemaColaborativoSeguranca::Application.routes.draw do
  
  resources :convites

  resources :comentarios

  resources :atendimentos

  resources :grupo_colaborativos do
    post 'remove_usuario'
  end

  resources :alarmes

  resources :sensors

  resources :tipo_sensors

  resources :enderecos

  devise_for :usuarios

  resources :usuarios do
    collection do 
      post :register_device
      post :unregister_device
    end
  end

  root :to => "sensors#index"

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  self.include_root_in_json = true
  attr_accessible :codigo, :localizacao, :status, :latitude, :longitude
  belongs_to :usuario
  belongs_to :tipo_sensor
  has_many :alarmes

  validates_presence_of :codigo
  validates_uniqueness_of :codigo
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_filter :authenticate_usuario!
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :localizacao %><br />
    <%= f.text_field :localizacao %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<h1>Listing sensors</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Localizacao</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sensors.each do |sensor| %>
  <tr>
    <td><%= sensor.codigo %></td>
    <td><%= sensor.localizacao %></td>
    <td><%= sensor.status %></td>
    <td><%= link_to 'Show', sensor %></td>
    <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
    <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @sensor.codigo %>
</p>

<p>
  <b>Localizacao:</b>
  <%= @sensor.localizacao %>
</p>

<p>
  <b>Status:</b>
  <%= @sensor.status %>
</p>


<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>